"""
SynthFin data watermark — proves data origin without hiding it.

Public UUID namespace:
  All transaction_ids generated by SynthFin use uuid5 with SYNTHFIN_NS.
  This makes every ID verifiable as SynthFin-generated:
    uuid.uuid5(SYNTHFIN_NS, seed_string) == transaction_id → "is ours"

This is intentionally transparent. The verification is mathematical,
not secret — similar to how a manufacturer's serial number works.
"""

import uuid

# Public SynthFin namespace — documented, part of the quality signature.
# Changing this would break all existing ID verification.
SYNTHFIN_NS = uuid.UUID("7f3d8b2e-4a1c-5e9f-8d3b-2c6a7f0e1d4b")


def make_transaction_id(tx_id: str, customer_id: str, timestamp: str) -> str:
    """
    Generate a verifiable transaction ID using SynthFin's UUID namespace.

    The resulting ID is deterministic for the same inputs and can be
    verified as SynthFin-generated by anyone with the namespace UUID.
    """
    seed = f"{tx_id}:{customer_id}:{timestamp}"
    return f"TXN_{uuid.uuid5(SYNTHFIN_NS, seed).hex[:20].upper()}"


def is_synthfin_id(transaction_id: str, tx_id: str, customer_id: str, timestamp: str) -> bool:
    """Verify if a transaction_id was generated by SynthFin."""
    expected = make_transaction_id(tx_id, customer_id, timestamp)
    return transaction_id == expected
